// Writes js/icons.js with the simple-icons paths the site uses (24×24 viewBox).
// Run after changing the list: npm run build:icons
import { writeFileSync } from 'node:fs';
import * as icons from 'simple-icons';

const SLUGS = [
  'javascript', 'typescript', 'vuedotjs', 'nuxt', 'react',
  'nodedotjs', 'express', 'python', 'flask', 'go',
  'mysql', 'postgresql', 'mongodb', 'r', 'jupyter',
  'macos', 'linux', 'git', 'gnubash',
  'github', 'medium',
];

const bySlug = Object.fromEntries(Object.values(icons).filter((i) => i && i.slug).map((i) => [i.slug, i]));
const out = {};
for (const slug of SLUGS) {
  if (!bySlug[slug]) throw new Error(`simple-icons has no "${slug}"`);
  out[slug] = bySlug[slug].path;
}
// Not in simple-icons: generic glyphs drawn for this site.
out.windows = 'M2 2h9.5v9.5H2zm10.5 0H22v9.5h-9.5zM2 12.5h9.5V22H2zm10.5 0H22V22h-9.5z';
out.linkedin = 'M3 3h18v18H3zM6.5 9.5V18h2.6V9.5zm1.3-4.1a1.5 1.5 0 1 0 0 3 1.5 1.5 0 0 0 0-3zM11 9.5V18h2.6v-4.4c0-1.2.4-2.1 1.6-2.1 1.1 0 1.4.8 1.4 2V18h2.6v-5c0-2.4-1.1-3.7-3.2-3.7-1.2 0-2 .6-2.4 1.2V9.5z';

writeFileSync(
  new URL('../js/icons.js', import.meta.url),
  `// Generated by tools/build-icons.mjs from simple-icons (CC0). Do not edit.\nexport const ICONS = ${JSON.stringify(out, null, 2)};\n`,
);
console.log(`js/icons.js: ${Object.keys(out).length} icons`);
